// <auto-generated />
using System;
using HrisApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HrisApi.Context.Migrations
{
    [DbContext(typeof(HrisApiContext))]
    partial class HrisApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HrisApi.Model.Access", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("Access");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            AccessCode = "AC01",
                            AccessName = "ALL-ACCESS",
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 86, DateTimeKind.Local).AddTicks(1983),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HrisApi.Model.BioLogs", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BioId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("BioLogs");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            BioId = 101,
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 106, DateTimeKind.Local).AddTicks(8486),
                            Date = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeCode = "1",
                            IsActive = true,
                            LogType = 0,
                            Time = "4:16 PM"
                        });
                });

            modelBuilder.Entity("HrisApi.Model.Branch", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("Branch");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            BranchCode = "TAY01",
                            BranchName = "TAYTAY",
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 90, DateTimeKind.Local).AddTicks(6665),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HrisApi.Model.CivilStatus", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CivilStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CivilStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("CivilStatus");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CivilStatusCode = "S",
                            CivilStatusName = "SINGLE",
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 98, DateTimeKind.Local).AddTicks(1786),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HrisApi.Model.Company", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CompanyAddress = "TAYTAY",
                            CompanyCode = "RRGO1",
                            CompanyName = "RRGO INC.",
                            ContactNumber = "123456789",
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 91, DateTimeKind.Local).AddTicks(2931),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HrisApi.Model.Department", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 91, DateTimeKind.Local).AddTicks(7860),
                            DepartmentCode = "IT01",
                            DepartmentName = "IT-SOFTWARE",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HrisApi.Model.EducationInfo", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CSAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CSCourse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CSInclusiveEndYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CSInclusiveStartYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CSName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ESAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESInclusiveEndYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESInclusiveStartYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HSAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HSInclusiveEndYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HSInclusiveStartYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HSName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PGSAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PGSCourse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PGSInclusiveEndYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PGSInclusiveStartYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PGSName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VSAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VSCourse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VSInclusiveEndYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VSInclusiveStartYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VSName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDNo");

                    b.ToTable("EducationInfo");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CSAddress = "TAYTAY, RIZAL",
                            CSCourse = "BS IN INFORMATION TECHNOLOGY",
                            CSInclusiveEndYear = "2018",
                            CSInclusiveStartYear = "2014",
                            CSName = "STI COLLEGE ORTIGAS - CAINTA",
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 97, DateTimeKind.Local).AddTicks(2871),
                            ESAddress = "TAYTAY, RIZAL",
                            ESInclusiveEndYear = "2008",
                            ESInclusiveStartYear = "2002",
                            ESName = "ROSARIO OCAMPO ELEM. SCHOOL",
                            EmployeeCode = "1",
                            HSAddress = "TAYTAY, RIZAL",
                            HSInclusiveEndYear = "2012",
                            HSInclusiveStartYear = "2008",
                            HSName = "JUAN SUMULONG MEMORIAL JR. COLLEGE",
                            VSAddress = "TAYTAY, RIZAL",
                            VSCourse = "CSDP",
                            VSInclusiveEndYear = "2014",
                            VSInclusiveStartYear = "2012",
                            VSName = "ACLC COLLEGE OF TAYTAY"
                        });
                });

            modelBuilder.Entity("HrisApi.Model.Employee", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BioId")
                        .HasColumnType("int");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegularized")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateResigned")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultShiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EducationInfoId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PersonalInfoId")
                        .HasColumnType("int");

                    b.Property<string>("PositionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDNo");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            BioId = 101,
                            BranchCode = "TAY01",
                            CompanyCode = "RRGO1",
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 94, DateTimeKind.Local).AddTicks(7892),
                            DateHired = new DateTime(2020, 12, 7, 16, 16, 38, 94, DateTimeKind.Local).AddTicks(5794),
                            DepartmentCode = "IT01",
                            EducationInfoId = 1,
                            EmployeeCode = "1",
                            EmployeeTypeCode = "R",
                            IsActive = true,
                            PersonalInfoId = 1,
                            PositionCode = "SOFTDEV",
                            Username = "webadmin"
                        });
                });

            modelBuilder.Entity("HrisApi.Model.EmployeeCustomSchedule", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("EmployeeCustomSchedule");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 103, DateTimeKind.Local).AddTicks(786),
                            Date = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeCode = "1",
                            IsActive = true,
                            ShiftCode = "TAYTAYS1"
                        });
                });

            modelBuilder.Entity("HrisApi.Model.EmployeeType", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("EmployeeType");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 93, DateTimeKind.Local).AddTicks(4644),
                            EmployeeTypeCode = "R",
                            EmployeeTypeName = "REGULAR",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HrisApi.Model.Gender", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 97, DateTimeKind.Local).AddTicks(7553),
                            GenderCode = "M",
                            GenderName = "MALE",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HrisApi.Model.Holiday", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolidayCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolidayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("Holiday");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 101, DateTimeKind.Local).AddTicks(322),
                            Date = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayCode = "1",
                            HolidayName = "CHRISTMAS DAY",
                            IsActive = true,
                            IsFixed = true
                        });
                });

            modelBuilder.Entity("HrisApi.Model.HolidayType", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolidayTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolidayTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("HolidayType");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 101, DateTimeKind.Local).AddTicks(6641),
                            HolidayTypeCode = "REGHOL",
                            HolidayTypeName = "REGULAR HOLIDAY",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HrisApi.Model.PersonalInfo", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CivilStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("PersonalInfo");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            Address = "TAYTAY RIZAl",
                            CivilStatusCode = "S",
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 95, DateTimeKind.Local).AddTicks(6227),
                            EmployeeCode = "1",
                            FirstName = "RAVI RENZ",
                            GenderCode = "M",
                            LastName = "OLAYRES",
                            MiddleName = "GONZAGA",
                            Mobile = "09352863548"
                        });
                });

            modelBuilder.Entity("HrisApi.Model.Position", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PositionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 92, DateTimeKind.Local).AddTicks(2354),
                            IsActive = true,
                            PositionCode = "SOFTDEV",
                            PositionName = "SOFTWARE DEVELOPER"
                        });
                });

            modelBuilder.Entity("HrisApi.Model.Shift", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Brk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GracePeriod")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoursWork")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRestday")
                        .HasColumnType("bit");

                    b.Property<string>("ND1ShiftIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ND1ShiftOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ND2ShiftIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ND2ShiftOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ND3ShiftIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ND3ShiftOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("Shift");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            Brk = 60.00m,
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 100, DateTimeKind.Local).AddTicks(751),
                            GracePeriod = 15.00m,
                            HoursWork = 8.00m,
                            IsActive = true,
                            IsRestday = false,
                            ND1ShiftIn = "18:00",
                            ND1ShiftOut = "22:00",
                            ND2ShiftIn = "22:00",
                            ND2ShiftOut = "02:00",
                            ND3ShiftIn = "02:00",
                            ND3ShiftOut = "06:00",
                            ShiftCode = "TAYTAYS1",
                            ShiftIn = "08:00",
                            ShiftName = "TAYTAY 08:00AM - 05:00PM",
                            ShiftOut = "17:00"
                        });
                });

            modelBuilder.Entity("HrisApi.Model.ShiftWeekly", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IDNo");

                    b.ToTable("ShiftWeekly");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 102, DateTimeKind.Local).AddTicks(2192),
                            Day = 1,
                            IsActive = true,
                            ShiftCode = "1"
                        });
                });

            modelBuilder.Entity("HrisApi.Model.User", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDNo");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 92, DateTimeKind.Local).AddTicks(6868),
                            IsActive = true,
                            Password = "masterpassword",
                            Username = "webadmin"
                        });
                });

            modelBuilder.Entity("HrisApi.Model.UserAccess", b =>
                {
                    b.Property<int>("IDNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDNo");

                    b.ToTable("UserAccess");

                    b.HasData(
                        new
                        {
                            IDNo = 1,
                            AccessCode = "1",
                            CreatedBy = "webadmin",
                            CreatedOn = new DateTime(2020, 12, 7, 16, 16, 38, 93, DateTimeKind.Local).AddTicks(385),
                            Username = "webadmin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
